-- Tabelle per utenti e sessioni digiuno (sostituiscono SQLite per deploy su Vercel)
-- Esegui in Supabase SQL Editor prima del deploy.

CREATE TABLE IF NOT EXISTS public.digiuno_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.digiuno_fast_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.digiuno_users(id) ON DELETE CASCADE,
  start_time timestamptz NOT NULL,
  end_time timestamptz
);

CREATE INDEX IF NOT EXISTS idx_digiuno_fast_sessions_user_id ON public.digiuno_fast_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_digiuno_fast_sessions_end_time ON public.digiuno_fast_sessions(end_time);

-- Reset classifica: una sola riga (id=1). reset_at = ultimo azzeramento; NULL = mai azzerata (conta tutto)
CREATE TABLE IF NOT EXISTS public.leaderboard_reset (
  id integer PRIMARY KEY DEFAULT 1,
  reset_at timestamptz
);
INSERT INTO public.leaderboard_reset (id, reset_at) VALUES (1, NULL) ON CONFLICT (id) DO NOTHING;

-- Vista classifica: conta solo sessioni con start_time >= reset_at (i tempi restano salvati in digiuno_fast_sessions)
CREATE OR REPLACE VIEW public.digiuno_leaderboard AS
SELECT t.id, t.username, t.created_at, t.total_hours, t.is_fasting, t.active_start_time
FROM (
  SELECT
    u.id,
    u.username,
    u.created_at,
    CAST(COALESCE((
      SELECT SUM(EXTRACT(EPOCH FROM (COALESCE(f.end_time, NOW()) - f.start_time)) / 3600.0)
      FROM public.digiuno_fast_sessions f
      WHERE f.user_id = u.id
        AND f.start_time >= COALESCE((SELECT reset_at FROM public.leaderboard_reset WHERE id = 1 LIMIT 1), '1970-01-01'::timestamptz)
    ), 0) AS NUMERIC) AS total_hours,
    EXISTS(
      SELECT 1 FROM public.digiuno_fast_sessions f2
      WHERE f2.user_id = u.id AND f2.end_time IS NULL
    ) AS is_fasting,
    (SELECT f3.start_time FROM public.digiuno_fast_sessions f3 WHERE f3.user_id = u.id AND f3.end_time IS NULL LIMIT 1) AS active_start_time
  FROM public.digiuno_users u
) t;
-- Tutti gli utenti in classifica: chi non ha mai digiunato appare con 0 ore e stato Pronto

-- Permessi: consenti lettura/scrittura con anon key (per l'app)
ALTER TABLE public.digiuno_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.digiuno_fast_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all digiuno_users" ON public.digiuno_users;
CREATE POLICY "Allow all digiuno_users" ON public.digiuno_users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all digiuno_fast_sessions" ON public.digiuno_fast_sessions;
CREATE POLICY "Allow all digiuno_fast_sessions" ON public.digiuno_fast_sessions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.leaderboard_reset ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all leaderboard_reset" ON public.leaderboard_reset;
CREATE POLICY "Allow all leaderboard_reset" ON public.leaderboard_reset FOR ALL USING (true) WITH CHECK (true);

-- Permesso lettura vista classifica (anon e authenticated)
GRANT SELECT ON public.digiuno_leaderboard TO anon;
GRANT SELECT ON public.digiuno_leaderboard TO authenticated;
GRANT SELECT ON public.digiuno_leaderboard TO service_role;
